"""Card proxies for acme-cards 0.1.0.

GENERATED by pihanga_remote.codegen from hand-written – do not edit.
"""
# ruff: noqa
from __future__ import annotations

from typing import Any, Callable, ClassVar, Literal, Optional, Union

from pydantic import Field as _Field

from pihanga_remote.card import CardModel, CardRef, EventContext, PropModel

LIBRARY = 'acme-cards'
LIBRARY_VERSION = '0.1.0'

# --- models (annotations are resolved lazily by model_rebuild below)

class AcmeGaugeResetEvent(PropModel):
    value: float


class Gauge(CardModel):
    """Card `acme/gauge` (acme-cards 0.1.0, module acme-cards)."""
    __card_type__: ClassVar[str] = 'acme/gauge'
    __events__: ClassVar[dict[str, str]] = {'on_reset': 'onReset'}
    __default_events_policy__: ClassVar[dict[str, dict[str, Any]]] = {}
    on_reset: Optional[Union[Callable[[AcmeGaugeResetEvent], Any], Callable[[AcmeGaugeResetEvent, EventContext], Any]]] = _Field(default=None, exclude=True, description='Handler for onReset (acme/gauge/reset)')
    label: Optional[str] = _Field(default=None)
    value: Optional[float] = _Field(default=None)
    max: Optional[float] = _Field(default=None)
    badge_card: Optional[CardRef] = _Field(default=None, alias='badgeCard', description='Optional card (any library) shown next to the gauge.')

# --- type aliases


# --- card metadata
Gauge.__event_payloads__ = {'onReset': AcmeGaugeResetEvent}

AcmeGaugeResetEvent.model_rebuild()
Gauge.model_rebuild()

CARDS: dict[str, type[CardModel]] = {c.__card_type__: c for c in [Gauge]}

__all__ = ['Gauge', 'CARDS', 'LIBRARY', 'LIBRARY_VERSION']
