/**
 * ES-module facade for "react/jsx-runtime" (a CommonJS package).
 * GENERATED by tools/gen-react-facades.cjs — shared via the import map so every
 * card library uses the SAME React instance as the runtime.
 */
import * as ns from "react/jsx-runtime";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const M: any = (ns as any).default ?? ns;
export default M;
export const Fragment = M.Fragment;
export const jsx = M.jsx;
export const jsxs = M.jsxs;
