/**
 * ES-module facade for "react" (a CommonJS package).
 * GENERATED by tools/gen-react-facades.cjs — shared via the import map so every
 * card library uses the SAME React instance as the runtime.
 */
import * as ns from "react";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const M: any = (ns as any).default ?? ns;
export default M;
export const Activity = M.Activity;
export const Children = M.Children;
export const Component = M.Component;
export const Fragment = M.Fragment;
export const Profiler = M.Profiler;
export const PureComponent = M.PureComponent;
export const StrictMode = M.StrictMode;
export const Suspense = M.Suspense;
export const ViewTransition = M.ViewTransition;
export const __CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE = M.__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE;
export const __COMPILER_RUNTIME = M.__COMPILER_RUNTIME;
export const act = M.act;
export const addTransitionType = M.addTransitionType;
export const cache = M.cache;
export const cacheSignal = M.cacheSignal;
export const captureOwnerStack = M.captureOwnerStack;
export const cloneElement = M.cloneElement;
export const createContext = M.createContext;
export const createElement = M.createElement;
export const createRef = M.createRef;
export const forwardRef = M.forwardRef;
export const isValidElement = M.isValidElement;
export const lazy = M.lazy;
export const memo = M.memo;
export const startTransition = M.startTransition;
export const unstable_useCacheRefresh = M.unstable_useCacheRefresh;
export const use = M.use;
export const useActionState = M.useActionState;
export const useCallback = M.useCallback;
export const useContext = M.useContext;
export const useDebugValue = M.useDebugValue;
export const useDeferredValue = M.useDeferredValue;
export const useEffect = M.useEffect;
export const useEffectEvent = M.useEffectEvent;
export const useId = M.useId;
export const useImperativeHandle = M.useImperativeHandle;
export const useInsertionEffect = M.useInsertionEffect;
export const useLayoutEffect = M.useLayoutEffect;
export const useMemo = M.useMemo;
export const useOptimistic = M.useOptimistic;
export const useReducer = M.useReducer;
export const useRef = M.useRef;
export const useState = M.useState;
export const useSyncExternalStore = M.useSyncExternalStore;
export const useTransition = M.useTransition;
export const version = M.version;
