/**
 * ES-module facade for "react-dom/client" (a CommonJS package).
 * GENERATED by tools/gen-react-facades.cjs — shared via the import map so every
 * card library uses the SAME React instance as the runtime.
 */
import * as ns from "react-dom/client";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const M: any = (ns as any).default ?? ns;
export default M;
export const createRoot = M.createRoot;
export const hydrateRoot = M.hydrateRoot;
export const version = M.version;
