/**
 * ES-module facade for "react-dom" (a CommonJS package).
 * GENERATED by tools/gen-react-facades.cjs — shared via the import map so every
 * card library uses the SAME React instance as the runtime.
 */
import * as ns from "react-dom";
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const M: any = (ns as any).default ?? ns;
export default M;
export const __DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE = M.__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE;
export const browser = M.browser;
export const createPortal = M.createPortal;
export const flushSync = M.flushSync;
export const preconnect = M.preconnect;
export const prefetchDNS = M.prefetchDNS;
export const preinit = M.preinit;
export const preinitModule = M.preinitModule;
export const preload = M.preload;
export const preloadModule = M.preloadModule;
export const requestFormReset = M.requestFormReset;
export const unstable_batchedUpdates = M.unstable_batchedUpdates;
export const useFormState = M.useFormState;
export const useFormStatus = M.useFormStatus;
export const version = M.version;
